### PR TITLE
update README.md to more clearly callout 4.20 merge

### PR DESCRIPTION
**Pull request by curiousercreative**
improvements for https://github.com/mwyborski/Linux-Magic-Trackpad-2-Driver/issues/42

### CODE REVIEW

**Comment by mwyborski** [comment]
@curiousercreative Thanks for your contribution! I will merge your PR, but i would like the first topic to be:
    # Driver is mainlined
instead of 
    # Look elsewhere

Can you change it? Otherwise i will do it.

**Comment by curiousercreative** [comment]
@mwyborski updated. Feel free to make any additional changes.

**Comment by curiousercreative** [comment]
@mwyborski bump, anything else you need on this?

**Comment by mwyborski** [comment]
@curiousercreative i am sorry! I merged it. Thank you very much!

**Pull request merged**
